apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-checkin-deployment
  namespace: orderly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-checkin
  template:
    metadata:
      labels:
        app: ms-checkin
    spec:
      containers:
      - name: ms-checkin-container
        image: dealmachine/checkin-api:5
        workingDir: /usr/checkin/api
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: ms-checkin-configmap
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          periodSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 3001
          periodSeconds: 5
          failureThreshold: 30
