apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-checkin-configmap
  namespace: orderly
data:
  PORT: "3001"
  NODE_ENV: "production"
  DB_HOST: "${DB_IP}" # db-service
  DB_USERNAME: "${DB_USERNAME}" # postgres
  DB_PORT: "5432"
  DB_PASSWORD: "${DB_PASSWORD}" # postgres
  DB_NAME: "${DB_NAME}" # postgres
  DB_DIALECT: postgres
